name: Deploy-ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: khays
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@master

      - name: Create envfile for backend
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: http://vardidze.ru:3000
          envkey_NEXTAUTH_URL_INTERNAL: http://vardidze.ru:3000
          file_name: .env

      - name: Copy env file to backend server
        uses: appleboy/scp-action@master
        with:
          host: vardidze.ru
          username: khays
          key: ${{ secrets.SERVER_SSH_PRYVATE_KEY }}
          source: ".env,docker-compose.yaml"
          target: "~/promtopia/"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: khays/promptopia-khays

      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: vardidze.ru
          username: khays
          key: ${{ secrets.SERVER_SSH_PRYVATE_KEY }}
          script: |
            cd ~/promtopia/ && docker-compose pull && \
            docker-compose up -d
